services:
    backend:
        container_name: backend
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ./:/code:z
        env_file:
            - .env
        depends_on:
            - postgres_backend
        ports:
            - "8000:8000"
        networks:
            - msio

    postgres_backend:
        container_name: postgres_backend
        image: postgres:16.3
        volumes:
            - postgres_backend:/var/lib/postgresql/data/
        env_file:
            - .env
        ports:
            - "5432:5432"
        networks:
            - msio

volumes:
    postgres_backend:

networks:
  msio:
    name: msio
    driver: bridge