"""add index to idx_id_inchi and cas_number

Revision ID: 83a343ab3a8f
Revises: 1da059e0c01f
Create Date: 2025-06-02 15:15:10.149456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83a343ab3a8f'
down_revision: Union[str, None] = '1da059e0c01f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_cas_number', 'metabolites', ['cas_number'], unique=False)
    op.create_index('idx_id_inchi', 'metabolites', ['id_inchi'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_id_inchi', table_name='metabolites')
    op.drop_index('idx_cas_number', table_name='metabolites')
    # ### end Alembic commands ###
