"""init db model

Revision ID: af48a994b95d
Revises: e66fb99ddb76
Create Date: 2025-06-02 12:26:21.398910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af48a994b95d'
down_revision: Union[str, None] = 'e66fb99ddb76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('users_email_idx'), 'users', ['email'], unique=True)
    op.create_index(op.f('users_id_idx'), 'users', ['id'], unique=False)
    op.create_index(op.f('users_username_idx'), 'users', ['username'], unique=True)
    op.create_table('metabolites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feature', sa.String(), nullable=False),
    sa.Column('identification_level', sa.Integer(), nullable=False),
    sa.Column('id_inchi', sa.String(), nullable=True),
    sa.Column('cas_number', sa.String(), nullable=True),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('sample_data', sa.String(), nullable=True),
    sa.Column('uploader_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], name=op.f('metabolites_uploader_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('metabolites_pkey')),
    sa.UniqueConstraint('cas_number', name='uniq_cas_number'),
    sa.UniqueConstraint('cas_number', name=op.f('metabolites_cas_number_key')),
    sa.UniqueConstraint('id_inchi', name='uniq_id_inchi'),
    sa.UniqueConstraint('id_inchi', name=op.f('metabolites_id_inchi_key'))
    )
    op.create_index(op.f('metabolites_feature_idx'), 'metabolites', ['feature'], unique=True)
    op.create_index(op.f('metabolites_id_idx'), 'metabolites', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('metabolites_id_idx'), table_name='metabolites')
    op.drop_index(op.f('metabolites_feature_idx'), table_name='metabolites')
    op.drop_table('metabolites')
    op.drop_index(op.f('users_username_idx'), table_name='users')
    op.drop_index(op.f('users_id_idx'), table_name='users')
    op.drop_index(op.f('users_email_idx'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
