"""change to float sample_data

Revision ID: 1da059e0c01f
Revises: af48a994b95d
Create Date: 2025-06-02 14:12:49.317286

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1da059e0c01f"
down_revision: Union[str, None] = "af48a994b95d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TABLE metabolites ALTER COLUMN sample_data TYPE DOUBLE PRECISION USING sample_data::double precision"
    )
    op.create_unique_constraint(
        op.f("metabolites_cas_number_key"), "metabolites", ["cas_number"]
    )
    op.create_unique_constraint(
        op.f("metabolites_id_inchi_key"), "metabolites", ["id_inchi"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("metabolites_id_inchi_key"), "metabolites", type_="unique")
    op.drop_constraint(
        op.f("metabolites_cas_number_key"), "metabolites", type_="unique"
    )
    op.alter_column(
        "metabolites",
        "sample_data",
        existing_type=sa.Float(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
